### ISSUE TITLE
Add Alternative instance for ParseT?

### ISSUE THREAD

**Issue by LiamGoodacre** [hdgarrood/aeson-better-errors#10]

**Comment by hdgarrood** [comment]
:+1:

**Comment by LiamGoodacre** [comment]
I was just about to implement this when I saw: https://github.com/hdgarrood/aeson-better-errors/blob/master/src/Data/Aeson/BetterErrors.hs#L111
> -- TODO Alternative?
-- use monoid, combine errors?
-- Simply take rightmost?
-- Or maybe take the one with the deepest path?
--
-- Or, export our own (<|>) that uses a semigroup (since errors are
-- 'nonempty') - that is, we don't want to allow failing with no error.

Given the reasoning of the last bit, should I try that instead?

**Comment by hdgarrood** [comment]
Ha, it was such a long time ago that I wrote that, I'd completely forgotten. Come to think of it I'm not sure how we could provide a way of combining errors, other than by returning a list of `ParseError`, and I don't think I want to do that, as it seems unnecessarily complex. Having `Alternative` would be nice but I think I'd rather provide a monomorphic `<|>` function, since there's no good definition for the `empty` class method from `Alternative`. I think my favourite approach would be to take the right side's error if both parsers error, what do you think?

**Comment by hdgarrood** [comment]
Resolved by #11.
